### ISSUE TITLE
Plugin doesn't support more than 1000 records

### ISSUE THREAD

**Issue by Patlatus** [Avinava/PageBlockTableEnhancerADV#1]
Looks like this plugin doesn't really support pagination, for example it doesn't support more than 1000 records.
Are you going to fix this in future releases?

**Comment by Avinava** [comment]
Have a look at this post http://blogforce9.blogspot.in/2014/10/showing-more-than-1k-records-using-pbe.html

**Comment by Patlatus** [comment]
Yay, it works.
However, it looks like page loading works very slowly. Even 1k records it loads longer than using original approach. Do you know the way to speed it up?
